#!/bin/bash

# calc script to compute base conversions and logic gate operations

# HELPER FUNCTIONS

# i made this a function as i had already reused it in 2 other functions so i thought this would be better code. it pads a string of characters with 0 according to a multiple u choose
# it checks whether the strings length is divisble by the multiple or not, if its not it sees how many 0's need to be padded to make the length divisble by the multiple.
pad_to_multiple() {
	local input="$1"
	local multiple="$2"

	local adds=0
	local len=${#input}

	while (( len % $multiple != 0 )); do
		(( len += 1 ))
		(( adds++ ))
	done

	local padding=""
	for (( i=0; i < $adds; i++ )); do
		padding="0${padding}"
	done

	input="${padding}${input}"

	echo "$input"
}

# PROGRAM & LOGIC FUNCTIONS

binary_to_decimal() {
	if [[ $(echo "$1" | tr -d ' ') =~ ^[01]+$ ]]; then # uses regex to check if $1 is a binary number (only containing 0 and 1)
		count=0
		result=0
		input=$(echo "$1" | tr -d ' ' | rev) # omits whitespace and reverses the string
		while read -n1 char; do # reads one character from $input each iteration
			if (( char == 1 )); then
				(( result += 2**count ))
			fi
			(( count++ ))
		done <<< "$input"
	else
		echo "input_error: invalid binary"
	fi

	echo "$result"
}

decimal_to_binary() {
	num=$1
	arrpos=0;
	declare -a result
	if [[ $1 =~ ^[0-9]+$ ]]; then # uses regex to check if $1 is a decimal number (only containing numbers from 0-9)
		if (( num == 0 )); then
			result[arrpos]=0
			(( arrpos++ ))
		else
			while (( num != 0 )); do
				if (( num % 2 == 0 )); then
					result[arrpos]=0
					(( arrpos++ ))
				else
					result[arrpos]=1
					(( arrpos++ ))
				fi
				num=$(( num / 2 ))
			done
		fi
	else
		echo "input_error: invalid decimal"
	fi

	result=$(echo "${result[@]}" | tr -d ' ' | rev)
	echo "$result"
}

hex_to_binary() {
	declare -a res_container
	index=0
        if [[ $(echo "$1" | tr -d ' ') =~ ^[0-9A-Fa-f]+$ ]]; then # uses regex to check if input is a hexadecimal (only containing 0-9 & A-F or a-f)
                while read -n1 char; do # reads one character from $1 each iteration
                        if [[ $char =~ ^[0-9]$ ]]; then # if statment that partitions logic if $char is 0-9, and else block for when $char is A-F
				res=$(decimal_to_binary $char)
				if [[ "${#res}" -lt 4 ]]; then
					padded_zeros="000$res" # 1 hex digit is 4 binary digits, so the decimal equivelant is padded with 3 zeros
					final_res=${padded_zeros: -4:4} # $padded_zeros is sliced from the 4th index from the end and read with 4 characters to get the 4 bit long binary
					res_container[$index]="$final_res"
					(( index++ ))
				else
					res_container[$index]="$res" # if outputted number is 4 bits long like 0b1000 which is equivelant to 8 in decimal
					(( index++ ))
				fi
			else
				case "$char" in # swtich case for when $char is A-F, hardcoded logic for A-F
					A | a)
						res_container[$index]="1010"
						(( index++ ))
						;;
					B | b)
						res_container[$index]="1011"
						(( index++ ))
						;;
					C | c)
						res_container[$index]="1100"
						(( index++ ))
						;;
					D | d)
						res_container[$index]="1101"
						(( index++ ))
						;;
					E | e)
						res_container[$index]="1110"
						(( index++ ))
						;;
					F | f)
						res_container[$index]="1111"
						(( index++ ))
						;;
				esac
			fi
                done <<< $(echo "$1" | tr -d ' ')
        else
                echo "input_error: invalid hexadecimal"
        fi

	result=$(echo ${res_container[@]})
	echo $result
}

binary_to_hex() {
	if [[ $(echo "$1" | tr -d ' ') =~ ^[01]+$ ]]; then
		declare -a res_container # array to store outputs (used in the other functions)
		index=0
		while read -n4 four; do # reads 4 characters from $1 each iteration
			[[ -z "$four" ]] && continue # edge case as read -n4 reads the newline character at the end which is a blank string
			reverse_four=$(echo "$four" | rev)
			count=0
			res=0
			while read -n1 char; do # reads 1 character from $char each iteration (nested while loop)
				if (( char == 1 )); then
					(( res += 2**count ))
					(( count++ ))
				else
					(( count++ ))
				fi
			done <<< "$reverse_four"

			if (( res <= 9 )); then # if block for numbers less than or equal 9, and else block for 10-15 which is A-F in hex
				res_container[$index]="$res"
				(( index++ ))
			else
				case "$res" in
					10)
						res_container[$index]="A"
						(( index++ ))
						;;
					11)
						res_container[$index]="B"
						(( index++ ))
						;;
					12)
						res_container[$index]="C"
						(( index++ ))
						;;
					13)
						res_container[$index]="D"
						(( index++ ))
						;;
					14)
						res_container[$index]="E"
						(( index++ ))
						;;
					15)
						res_container[$index]="F"
						(( index++ ))
						;;
				esac
			fi
		done <<< $(echo "$1" | tr -d ' ')
	else
		echo "input_error: invalid binary"
	fi
	result=$(echo "${res_container[@]}" | tr -d ' ')
	echo "$result"
}

binary_to_octal() {
	local -a res_container
	local index=0
	local input=$(echo "$1" | tr -d ' ')

	if [[ "$input" =~ ^[01]+$ ]]; then # regex to check if a number is binary (only contains 0 or 1)

# this if statment is triggered when the binary input length is not divisble by 3 which causes issues as the while loop takes chunks of 3 from the left
# which will output the wrong octal equivelants and so this if statment works to find exactly what amount of padding 0's the binary needs to be ready for the while loop

		if (( ${#input} % 3 != 0 )); then
			input=$(pad_to_multiple "$input" 3)
		fi

		while read -n3 three; do
			[[ -z "$three" ]] && continue # edge case as read -n4 reads the newline character at the end which is a blank string

				local oct=$(binary_to_decimal $three) # uses binary_to_decimal() func so it turns 3 digit binary numbers 000-111 to decimal numbers from 0-7 which are basically octal
				res_container[$index]=$oct
				(( index++ ))
		done <<< $input
	else
		echo "input_error: invalid binary"
	fi

	local result=$(echo ${res_container[@]} | tr -d ' ')
	echo $result
}

octal_to_binary() {
	local input=$(echo "$1" | tr -d ' ')

	if [[ $input =~ ^[0-7]+$ ]]; then # regex to check if input is octal (only numbers between 0 and 7)

		local -a res_container
		local index=0

		while read -n1 char; do
			[[ -z $char ]] && continue

			bin=$(decimal_to_binary $char) # turns octal number (0-7) using decimal_to_binary() function

# this if statment checks if the outputted binary number is of length < 3, as each octal number is equivelant to 3 binary digits, so it should be padded with 0's if its not
			if (( ${#bin} < 3 )); then
				padded_bin="00$bin"
				final_bin=${padded_bin: -3:3}

				res_container[$index]=$final_bin
				(( index++ ))
			else
				res_container[$index]=$bin
				(( index++ ))
			fi
		done <<< $input
	else
		echo "input_error: invalid octal"
	fi

	result=$(echo ${res_container[@]} | tr -d ' ')
	echo "$result"
}

decimal_to_hex() {
	input=$(echo "$1" | tr -d ' ')
	bin=$(decimal_to_binary $input)

	if (( ${#bin} % 4 != 0 )); then
		bin=$(pad_to_multiple "$bin" 4)
	fi

	hex=$(binary_to_hex $bin)

	echo $hex
}

hex_to_decimal() {
	input=$(echo "$1" | tr -d ' ')
	bin=$(hex_to_binary $input)

	dec=$(binary_to_decimal "$bin")

	echo $dec
}

decimal_to_octal() {
	input=$(echo "$1" | tr -d ' ')
	bin=$(decimal_to_binary $input)

	oct=$(binary_to_octal "$bin")

	echo $oct
}

octal_to_decimal() {
	input=$(echo "$1" | tr -d ' ')
	bin=$(octal_to_binary $input)

	dec=$(binary_to_decimal "$bin")

	echo $dec
}

hex_to_octal() {
	input=$(echo "$1" | tr -d ' ')
	bin=$(hex_to_binary $input)

	oct=$(binary_to_octal "$bin")

	echo $oct
}

octal_to_hex() {
	input=$(echo "$1" | tr -d ' ')
	bin=$(octal_to_binary $input)

	hex=$(binary_to_hex "$bin")

	echo $hex
}

# program running logic, reading flags and user input (only reads positional parameters)
# not programmed to read from stdin in pipelines or to read from files yet

case "$1" in
	"-bd")
		result=$(binary_to_decimal "$2")
		echo "$result"
		;;
	"-db")
		result=$(decimal_to_binary "$2")
		echo "$result"
		;;
	"-hb")
		result=$(hex_to_binary "$2")
		echo "$result"
		;;
	"-bh")
		result=$(binary_to_hex "$2")
		echo "$result"
		;;
	"-bo")
		result=$(binary_to_octal "$2")
		echo "$result"
		;;
	"-ob")
		result=$(octal_to_binary "$2")
		echo "$result"
		;;
	"-dh")
		result=$(decimal_to_hex "$2")
		echo "$result"
		;;
	"-hd")
		result=$(hex_to_decimal "$2")
		echo "$result"
		;;
	"-do")
		result=$(decimal_to_octal "$2")
		echo "$result"
		;;
	"-od")
		result=$(octal_to_decimal "$2")
		echo "$result"
		;;
	"-ho")
		result=$(hex_to_octal "$2")
		echo "$result"
		;;
	"-oh")
		result=$(octal_to_hex "$2")
		echo "$result"
		;;
	"-kmap")
		if (( $# - 1 == 2 )); then
			if [[ ${#2} -eq 1 ]] && (( $2 >= 1 && $2 <= 4 )); then
				if [[ $3 =~ ^[01]+$ ]] && (( ${#3} == 2**$3 )); then
					./kmap.exe "$2" "$3" # will work when kmap.cpp is done and compiled (will never happen)
				else
					echo "paramter_error: table_elments are either more or less than $(( $3 * $3 )). table_elements should also be 0/1"
				fi
			else
				echo "parameter_error: invalid variable_amount length (1 through 4)"
			fi
		else
			echo "parameter_error: not enough parameters. (-kmap <variable_amount> <table_elements>)"
		fi
		;;
	*)
		echo "flag_error: unrecognized flag"
		;;
esac
